if (context.session.BotContext.ultratax === true && context.session.BotContext.onvio !== true) 
{ print("Error".bold() + "\n" 
+ "Database Validation Error: /Return/ReturnHeader/OriginatorGrp/EFIN: Electronic Filing Ident ification Number (EFIN) in the Return Header must be listed in the e-File database and in accepted status. (value xxxxxx, rule R0000-905-01)" + 
"\n\nNote: ".bold() + "The value represents the EFIN that is being rejected." + 
"\n\nTax years affected".bold() + "\nThis rejection applies to 2019, 2020, and 2021 tax returns." + 
"\n\nCause".bold() + 
"\nThis rejection indicates that the EFIN used to file the return is not approved to file a 1041 return according to the IRS e-file database." + 
"\n\nSolution".bold() + 
"\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Go to Setup and select Office Configuration.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Go to the E-filing tab. " + "Note: ".bold() + " If " + "Several EFINs are being used ".bold() + "is selected, go to the Preparers tab instead to ver ify the EFIN for the preparer assigned to the return.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Make sure the correct EFIN is entered.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. If it is incorrect, correct it, then re-create and retransmit the return.\n\n If you change the EFIN to a number not registered with Thomson Reuters, you need to [submit your e-file summary for approval](https://cs.thomsonreuters.com/ua/ut/2018_cs_us_en/utwapp/kb/elf-all-entities-e-file-application-summary-and-efin-faqs.htm){submit your e-file summary for approval} before you can e-file. if the correct EFIN was used, call the IRS e-help Desk at 866.255.0654 to ver ify that you are approved to electronically file 1041 returns. \n" + "Note:".bold() + " With this error you may also receive the IRS Letter 5903. If you receive this letter, follow the instructions on the [IRS website](https://www.irs.gov/individuals/important-update-about-your-eservices-account){IRS website} to re-activate your e-Services account. [Read the article](https://cs.thomsonreuters.com/ua/ut/e-file/1041/e-file-error-codes/r0000-905.htm){Read the article} on the Help & How-To Center.") } 


else { print("Error".bold() + "\n\n" + "Database Validation Error: /Return/ReturnHeader/OriginatorGrp/EFIN: Electronic Filing Ident ification Number (EFIN) in the Return Header must be listed in the e-File database and in accepted status. (value xxxxxx, rule R0000-905-01)" + "\n\nNote:".bold() + " The value represents the EFIN that is being rejected." + "\n\nTax years affected".bold() + "\n\nThis rejection applies to 2019, 2020, and 2021 tax returns." + "\n\nCause".bold() + "\n\nThis rejection indicates that the EFIN used to file the return is not approved to file a 1041 return according to the IRS e-file database." + "\n\nSolution".bold() + "\n\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;  In Onvio Center, go to Setup.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;  Select Firm.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;  Go to the USTAX tab.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;   if it is incorrect, correct it, then re-create and resubmit the electronic file.\n\n if you change the EFIN to a number not registered with Thomson Reuters, you may need to [submit your e-file summary for approval](https://onvio.us/ua/help/us-en/staff/tax/2018/elf/tasks/submit-irs-e-file-application.htm){submit your e-file summary for approval} before you can e-file.\n\n if the EFIN on the USTAX tab does not match the EFIN in the value in the rejection, that indicates that the preparer's EFIN is being used to electronically file. To check the preparer's EFIN:\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;  Go the Onvio Center and select Setup.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;  Select Staff.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;  Select the preparer assigned to the return.\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;  Click Edit\n &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;  Click the Roles tab.\n\n if the correct EFIN was used, call the IRS e-help Desk at 866.255.0654 to ver ify that you are approved to electronically file 1041 returns.\n\n[Read the article](https://onvio.us/ua/help/us-en/staff/tax/e-file/1041/e-file-error-codes/r0000-905.htm){Read the article} on the Help & How-To Center.") }